### ISSUE TITLE
Add variables for DB names

### ISSUE THREAD

**Issue by FalkoInc** [AVENTER-UG/docker-ispconfig#1]
Howdy,
it would be great to be able to set view more DB variables in the docker compose file.

https://github.com/AVENTER-UG/docker-ispconfig/blob/master/autoinstall.ini
mysql_root_user=root
mysql_database=dbispconfig
mysql_master_root_user=root
mysql_master_database=dbispconfig

to

mysql_root_user=$isp_mysql_root_user
mysql_database=$isp_mysql_database
mysql_master_root_user=$isp_mysql_master_root_user
mysql_master_database=$isp_mysql_master_database

and add
https://github.com/AVENTER-UG/docker-ispconfig/blob/master/Dockerfile
ENV isp_mysql_root_user root
ENV isp_mysql_database dbispconfig
ENV isp_mysql_master_root_user root
ENV isp_mysql_master_database dbispconfig

Thank you kindly
Falko

**Comment by andreaspeters** [comment]
Hi Falko,

thanks for rise a issue. I will add these parameters as variable. :+1: 

Cheers,
Andreas
